apiVersion: v1
kind: Service
metadata:
  name: docker-case-study
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: docker-case-study
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
